platform :ios, '9.0'

target 'SwipeSpeak' do
  use_frameworks!

  pod 'DZNEmptyDataSet',  '~> 1.8.1'
  pod 'Zephyr',           '~> 3.1.2'
  pod 'MarkdownView',     '~> 1.2.0'

  pod 'Firebase/Core'

  pod 'Fabric',           '~> 1.7.6'
  pod 'Crashlytics',      '~> 3.10.1'
end
